app.elastic:
  host: 127.0.0.1
  port: 9200
  portAlternate: 9201
      
discogs:
  url: https://api.discogs.com/database/search
  token: bGgeOLmUZGCiDThWTbqIcpcpyXkzizJQIDHOnCNu
  
album-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8080
    
server:
  port: 8081    