app.elastic:
  host: elasticsearch-v6
  port: 9200
  portAlternate: 9201
      
discogs:
  url: https://api.discogs.com/database/search
  token: bGgeOLmUZGCiDThWTbqIcpcpyXkzizJQIDHOnCNu
  

server:
  port: 8081    
  
artist-service:
  url: http://artist-service:8080